// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use session pooler (port 5432) for migrations/DDL — switch to DATABASE_URL for runtime
    url: process.env["DIRECT_URL"],
  },
});
