/**
 * Operational Calendar — shared vocabulary and event contracts.
 *
 * Canonical terminology for the Schedule / Operational Calendar system.
 * This is the single source of truth for event types, source policy,
 * editability rules, and status vocabulary used across the calendar feature.
 *
 * Design rules:
 *  - All event-type additions must be added here first.
 *  - UI visibility and capability surfacing must derive from CalendarEventType,
 *    not from hardcoded per-industry checks.
 *  - No schema specifics in this file — contracts only.
 *
 * Relationship to other features:
 *  - Intake sessions  →  src/features/intake/* (linked via CalendarEventType.intake_session)
 *  - Staff data       →  src/features/staff/*  (linked via CalendarEventType.staff_shift)
 *  - Suppliers        →  src/features/receiving/* (linked via CalendarEventType.delivery_window)
 *  - Income providers →  src/features/integrations/* (external events via provider sync)
 */

// ---------------------------------------------------------------------------
// Event type model
// ---------------------------------------------------------------------------

/**
 * All recognized calendar event types.
 *
 * Used to:
 *  - drive capability-gated UI sections (which event types are visible/creatable)
 *  - normalize external provider events into canonical internal types
 *  - link internal system events (intake sessions, staff shifts) into the calendar
 */
export const CALENDAR_EVENT_TYPES = [
  "appointment",      // client/service booking
  "reservation",      // table, room, or resource reservation
  "staff_shift",      // staff work schedule block
  "job_assignment",   // contractor job site booking
  "delivery_window",  // supplier delivery / intake timing window
  "intake_session",   // inventory intake session (linked from Intake Hub)
  "manual_block",     // user-created time block (no linked entity)
  "pickup_reservation", // customer pickup slot (retail)
] as const;

export type CalendarEventType = (typeof CALENDAR_EVENT_TYPES)[number];

// ---------------------------------------------------------------------------
// Event source policy
// ---------------------------------------------------------------------------

/**
 * Where an event originates.
 *  - manual:   created directly by the user inside this app
 *  - internal: generated by another feature within this app (intake, staff, etc.)
 *  - provider: synced from an external calendar or scheduling platform
 */
export const CALENDAR_EVENT_SOURCES = ["manual", "internal", "provider"] as const;

export type CalendarEventSource = (typeof CALENDAR_EVENT_SOURCES)[number];

// ---------------------------------------------------------------------------
// Editability policy
// ---------------------------------------------------------------------------

/**
 * Whether an event can be modified by the user.
 *  - editable:   user can update or delete this event
 *  - read_only:  event is locked (e.g. synced from external provider)
 *  - restricted: event is owned by another entity (e.g. internal intake session)
 */
export const CALENDAR_EVENT_EDITABILITY = ["editable", "read_only", "restricted"] as const;

export type CalendarEventEditability = (typeof CALENDAR_EVENT_EDITABILITY)[number];

/**
 * Default editability policy by source.
 * Applied when no per-event override is present.
 */
export const DEFAULT_EDITABILITY_BY_SOURCE: Record<CalendarEventSource, CalendarEventEditability> = {
  manual:   "editable",
  internal: "restricted",
  provider: "read_only",
};

// ---------------------------------------------------------------------------
// Event status vocabulary
// ---------------------------------------------------------------------------

export const CALENDAR_EVENT_STATUSES = [
  "scheduled",   // confirmed and on the calendar
  "tentative",   // not yet confirmed
  "cancelled",   // explicitly cancelled (kept for audit)
  "completed",   // occurred in the past and closed
] as const;

export type CalendarEventStatus = (typeof CALENDAR_EVENT_STATUSES)[number];

// ---------------------------------------------------------------------------
// Calendar view modes
// ---------------------------------------------------------------------------

export const CALENDAR_VIEW_MODES = ["day", "week", "month"] as const;

export type CalendarViewMode = (typeof CALENDAR_VIEW_MODES)[number];

export const DEFAULT_CALENDAR_VIEW: CalendarViewMode = "week";

// ---------------------------------------------------------------------------
// Canonical event shape (contracts only — no DB-specific fields)
// ---------------------------------------------------------------------------

/**
 * The canonical shape of a calendar event as used by the UI and service layer.
 * Not a Prisma model — this is the normalized presentation contract.
 */
export interface CalendarEventSummary {
  id: string;
  businessId: string;
  title: string;
  eventType: CalendarEventType;
  source: CalendarEventSource;
  editability: CalendarEventEditability;
  status: CalendarEventStatus;
  startAt: Date;
  endAt: Date;
  /** IANA timezone string, e.g. "America/Toronto" */
  timezone: string;
  /** Optional: linked staff member */
  staffId?: string | null;
  /** Optional: linked supplier or resource entity */
  resourceId?: string | null;
  /** Optional: linked customer/supplier/job entity */
  linkedEntityId?: string | null;
  /** For provider events: the originating provider key */
  providerKey?: string | null;
  /** For provider events: the provider's own event ID (for dedupe) */
  externalId?: string | null;
}

// ---------------------------------------------------------------------------
// Industry-to-event-type capability map
// ---------------------------------------------------------------------------

/**
 * Maps each industry type to the set of CalendarEventTypes that are
 * emphasized (visible by default) for that industry.
 *
 * All event types remain creatable regardless of industry — this drives
 * default surface emphasis only, not hard gating.
 */
export const CALENDAR_EVENT_EMPHASIS_BY_INDUSTRY: Record<string, CalendarEventType[]> = {
  restaurant:  ["reservation", "delivery_window", "staff_shift", "manual_block"],
  salon:       ["appointment", "staff_shift", "manual_block"],
  contractor:  ["job_assignment", "delivery_window", "staff_shift", "manual_block"],
  retail:      ["pickup_reservation", "delivery_window", "staff_shift", "manual_block"],
  general:     ["appointment", "delivery_window", "staff_shift", "manual_block"],
};
